version: '3.8'

services:
  msgsched:
    #build: .
    image: ghcr.io/driftywinds/msgsched
    container_name: msgsched
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Kolkata
    env_file:
      - .env
    working_dir: /app
    healthcheck:
      test: ["CMD", "pgrep", "-f", "msgsched"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s