version: "3.9"

services:
  msgsched:
    image: ghcr.io/driftywinds/msgsched
    container_name: msgsched
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./schedules.db:/app/schedules.db

    environment:
      TZ: Asia/Kolkata
